module.exports = {
  content: ["./src/**/*.html", "./src/**/*.vue"],
  safelist: [
    "slide-right-enter-from",
    "slide-right-enter-active",
    "slide-right-leave-active",
    "slide-right-leave-to",
    "slide-left-enter-from",
    "slide-left-enter-active",
    "slide-left-leave-active",
    "slide-left-leave-to",
    "fade-enter-from",
    "fade-enter-active",
    "fade-leave-active",
    "fade-leave-to",
  ],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: "3px",
      },
      boxShadow: {
        "md-up":
          "0 -4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
      },
      colors: {
        blue: {
          600: "#093E5D",
          500: "#004F8F",
          450: "#236AA3",
          400: "#6CACE0",
          300: "#B1D7F6",
          200: "#D1E8FA",
          100: "#EFF8FF",
        },
        cadetBlue: {
          500: "#477276",
          400: "#76A8AD",
          300: "#BAD6D8",
          200: "#DBEAEB",
          100: "#EEF5F6",
        },
        gray: {
          800: "#1f2937",
          400: "#64768E",
          350: "#95A8C1",
          300: "#C2CEDB",
          200: "#DCDFE1",
          100: "#F2F2F3",
        },
        green: {
          600: "#085A43",
          500: "#1E8F6F",
        },
        maroon: {
          500: "#482842",
          200: "#e1d0d8",
        },
        red: {
          500: "#9E1946",
          300: "#D66289",
          200: "#D8BAC4",
          100: "#F6EEF1",
        },
        yellow: {
          550: "#ECA409",
          500: "#F8BA34",
          400: "#FED943",
          350: "#E7D088",
          300: "#EFDFAE",
          200: "#F8EBC3",
          100: "#FFFBF0",
        },
      },
      fontFamily: {
        mono: [
          '"Roboto Mono"',
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
        sans: [
          '"Red Hat Text"',
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      fontSize: {
        "2xs": ".625rem",
        "4xl": "2rem",
        "5xl": "2.5rem",
      },
      gridColumn: {
        "span-full": "full-start / full-end",
        "span-content": "content",
        "span-start-half": "start-half",
        "span-end-half": "end-half",
        "span-full-start-half": "full-start / start-half-end",
        "span-full-end-half": "start-half-end / full-end",
      },
      height: {
        4.5: "1.125rem",
        22: "5.5rem",
        25: "6.25rem",
      },
      inset: {
        "-px": "-1px",
        "full-minus-px": "calc(100% - 1px)",
      },
      lineHeight: {
        2: "0.5rem",
        13: "3.5rem",
      },
      margin: {
        1.75: "0.4375rem",
        4.5: "1.125rem",
      },
      maxWidth: {
        "2xs": "16rem",
        "screen-3xl": "1920px",
      },
      minHeight: {
        6: "1.5rem",
        12: "3rem",
        44: "11rem",
      },
      minWidth: {
        6: "1.5rem",
        18: "4.5rem",
        72: "18rem",
        "screen-xl": "1280px",
        "screen-dominion-laptop": "1279px",
      },
      padding: {
        4.5: "1.125rem",
        18: "4.5rem",
      },
      spacing: {
        4.5: "1.125rem",
      },
      translate: {
        "-3px": "-3px",
      },
      width: {
        4.5: "1.125rem",
        18: "4.5rem",
        25: "6.25rem",
      },
      zIndex: {
        "-1": "-1",
        60: 60,
        70: 70,
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ["disabled", "group-focus"],
      borderWidth: ["hover", "last"],
      borderColor: ["disabled"],
      cursor: ["disabled"],
      textAlign: ["last"],
      textColor: ["disabled", "group-focus"],
      padding: ["first", "last"],
      opacity: ["group-focus"],
    },
  },
  plugins: [],
};
