source "https://rubygems.org"

ruby "3.3.7"

gem 'dotenv-rails', groups: [:development, :test]

gem "rails", "~> 8.0.2", ">= 8.0.2"
gem "puma", ">= 5.0"
gem "redis", ">= 4.0.1"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "stringio", ">= 3.1.6"  # just required because of ambiguity
gem "pg"
gem "bootsnap", require: false
gem "rack-cors"
gem "sidekiq"
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.12.1"
gem "blueprinter", "~> 1.1"
gem 'pry-rails'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end


